### ISSUE TITLE
GSL interpolation error

### ISSUE THREAD

**Issue by tribhu451** [derekeverett/iS3D#57]
I used a boost invariant(2+1D) hypersurface file from MUSIC and tried to run the code. but it's showing an error of following type:

[.......]
Reading in freezeout surface in (new) public MUSIC boost invariant format
Loading particle info from urqmd/smash pdg file (check that only 1 blank line at end of file)
...using read_resonances_conventional() 

There are 327 resonances: 77 mesons, 125 baryons and 125 antibaryons

Last particle: mcid = -12110, Anti-baryon-n-2250, m = 2.250000 GeV (please check this) 

Reading in 14 moment and Chapman-Enskog coefficient tables...done
gsl: interp.c:83: ERROR: x values must be strictly increasing
Default GSL error handler invoked.
Aborted (core dumped)

**Comment by mjmcnelis** [comment]
Hi Tribhuban,

It looks like this error occured when you test/print the df coefficients using the averaged temperature. You can check thermodynamic_quantities.dat to see if the average temperature [GeV] (first row) is what you expected. 

If the value looks wrong, then your surface file and read-in format may be inconsistent so it's important to double-check the columns. I believe the MUSIC format (mode = 6) has the columns

[t x y n ds_t/t ds_x/t ds_y/t ds_n/t u^t u^x u^y t.u^n E T muB muS muC (E+P)/T pi^tt pi^tx pi^ty t.pi^tn pi^xx pi^xy t.pi^xn pi^yy t.pi^yn t2.pi^nn Pi]

If you're still having issues, you can send a snippet of the surface file and parameter file to my email mcnelis.9@osu.edu.

Hope this helps,
Mike

**Comment by mjmcnelis** [comment]
Based on what you sent me, it looks like you're missing muS and muC above (strange and charm chemical potential). You're surface file is short by two columns, so your average temperature went nan instead of ~ 0.135 GeV.

I'm not sure what parameter in MUSIC is needed to include {muS muC} in the surface since I never used the code myself. You should ask Derek, Chun or J.F.

In the meantime you can try commenting l.738 - 739 in readindata.cpp

- Mike

**Comment by tribhu451** [comment]
Thanks Micheal. I  just took a single row of 'surface.dat' file and put 0,0 in the place of muS and muC . Now it's working fine.
